# Generated by Django 3.2.12 on 2024-03-23 10:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refer',
            name='users',
            field=models.ManyToManyField(related_name='Referers', to=settings.AUTH_USER_MODEL),
        ),
    ]
