# Generated by Django 3.2.12 on 2024-03-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_refer_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
